name: Deploy to Fly.io

on:
  ## Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:

  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: gru
  FLY_ORG: personal

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: superfly/fly-pr-review-apps@1.0.0
